title: "Understanding MoE Models through Internal Mechanisms"
url: "https://yingjiahao14.github.io"
baseurl: "/MoE-MUI"  # set your GitHub Pages URL if you have a custom domain
lang: en
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# We use a very thin base; layout and CSS provide the look & feel.
# You can switch to a GitHub Pages theme if you prefer:
# remote_theme: pages-themes/minimal@v0.2.0

# Build settings
markdown: kramdown
kramdown:
  input: GFM


